version: '3.4'

services:
  # 1. THE WAREHOUSE (Postgres)
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  # 2. THE DATA LAKE (MinIO)
  minio:
    image: minio/minio
    entrypoint: ["/bin/sh", "-c", "mkdir -p /data/raw-data && /usr/bin/minio server /data --console-address ':9001'"]
    environment:
      - MINIO_ROOT_USER=minio_admin
      - MINIO_ROOT_PASSWORD=minio_secret
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Browser UI port
    volumes:
      - ./minio_data:/data

  # 3. THE ORCHESTRATOR (Airflow)
  airflow-webserver:
    image: apache/airflow:2.7.1
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      # --- FIX 403 ERROR ---
      - AIRFLOW__WEBSERVER__SECRET_KEY=my_very_secret_key_fix_403
    volumes:
      - ./dags:/opt/airflow/dags
      - ./ml_script:/opt/airflow/ml_script
      - ./dbt_project:/opt/airflow/dbt_project
      - ./requirements.txt:/opt/airflow/requirements.txt
    ports:
      - "8080:8080"
    command: bash -c "airflow db init && airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com && airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.7.1
    depends_on:
      - airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      # --- FIX 403 ERROR (Harus sama dengan webserver) ---
      - AIRFLOW__WEBSERVER__SECRET_KEY=my_very_secret_key_fix_403
    volumes:
      - ./dags:/opt/airflow/dags
      - ./ml_script:/opt/airflow/ml_script
      - ./dbt_project:/opt/airflow/dbt_project
      - ./requirements.txt:/opt/airflow/requirements.txt
    command: bash -c "pip install -r /opt/airflow/requirements.txt && airflow scheduler"